### ISSUE TITLE
Error with TypeScript when running npm run storybook

### ISSUE THREAD

**Issue by AIVIETNAM-AIO-ANHTUANPHAM** [redplane/cms-ui-bs#1]
@redplane I got into trouble while integrating storybook into the project regarding the e2e.spec.ts .
It seems like storybook make use of Jest test framework, but following the instructions https://www.learnstorybook.com/intro-to-storybook/angular/en/get-started/ will result in an error saying it cannot parse the Jest functions.

**Comment by redplane** [comment]
The issue was caused by the conflict between **jest** and **jasmine** framework.
In master branch, jasmine already removed from the project. Right now, `npm run storybook` works smoothly.
